---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:
    # Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    # Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker

    # Use command module
  - name: Update setup.kibana in /etc/metricbeat/metricbeat.yml
    replace:
      path: /etc/metricbeat/metricbeat.yml
      regexp: '(\s+)#host: "localhost:5601"(\s+.*)?$'
      replace: '\1host: "10.2.0.4:5601"\2'
      backup: yes

  - name: Update output.elasticsearch in /etc/metricbeat/metricbeat.yml
    replace:
      path: /etc/metricbeat/metricbeat.yml
      regexp: '(\s+)hosts: \["localhost:9200"\](\s+.*)?$'
      replace: '\1hosts: ["10.2.0.4:9200"]\2'
      backup: yes

    # Use command module
  - name: start metric beat
    command: service metricbeat start

    # Use systemd module
  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes